
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.attr
{
public sealed partial class ActorBaseAttr : Luban.BeanBase
{
    public ActorBaseAttr(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
        Desc = _buf.ReadString();
        STR = _buf.ReadInt();
        CON = _buf.ReadInt();
        AGI = _buf.ReadInt();
        WIL = _buf.ReadInt();
        INT = _buf.ReadInt();
    }

    public static ActorBaseAttr DeserializeActorBaseAttr(ByteBuf _buf)
    {
        return new attr.ActorBaseAttr(_buf);
    }

    /// <summary>
    /// 名字（唯一标识）
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 气力
    /// </summary>
    public readonly int STR;
    /// <summary>
    /// 根骨
    /// </summary>
    public readonly int CON;
    /// <summary>
    /// 身法
    /// </summary>
    public readonly int AGI;
    /// <summary>
    /// 定力
    /// </summary>
    public readonly int WIL;
    /// <summary>
    /// 悟性
    /// </summary>
    public readonly int INT;
   
    public const int __ID__ = 1745311770;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "desc:" + Desc + ","
        + "STR:" + STR + ","
        + "CON:" + CON + ","
        + "AGI:" + AGI + ","
        + "WIL:" + WIL + ","
        + "INT:" + INT + ","
        + "}";
    }
}
}

