
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.attr
{
public sealed partial class BaseAttr : Luban.BeanBase
{
    public BaseAttr(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        HP = _buf.ReadFloat();
        MP = _buf.ReadFloat();
        ATKp = _buf.ReadFloat();
        ATKm = _buf.ReadFloat();
        DEFp = _buf.ReadFloat();
        DEFm = _buf.ReadFloat();
        SPD = _buf.ReadFloat();
        PenP = _buf.ReadFloat();
        PenM = _buf.ReadFloat();
        HIT = _buf.ReadFloat();
        EVA = _buf.ReadFloat();
        CR = _buf.ReadFloat();
        CD = _buf.ReadFloat();
        PAR = _buf.ReadFloat();
        PDR = _buf.ReadFloat();
        CTR = _buf.ReadFloat();
        RES = _buf.ReadFloat();
    }

    public static BaseAttr DeserializeBaseAttr(ByteBuf _buf)
    {
        return new attr.BaseAttr(_buf);
    }

    /// <summary>
    /// 属性唯一标识
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 气血
    /// </summary>
    public readonly float HP;
    /// <summary>
    /// 真气/内力
    /// </summary>
    public readonly float MP;
    /// <summary>
    /// 外攻
    /// </summary>
    public readonly float ATKp;
    /// <summary>
    /// 内攻
    /// </summary>
    public readonly float ATKm;
    /// <summary>
    /// 外防
    /// </summary>
    public readonly float DEFp;
    /// <summary>
    /// 内防
    /// </summary>
    public readonly float DEFm;
    /// <summary>
    /// 行动速度
    /// </summary>
    public readonly float SPD;
    /// <summary>
    /// 破甲
    /// </summary>
    public readonly float PenP;
    /// <summary>
    /// 破气
    /// </summary>
    public readonly float PenM;
    /// <summary>
    /// 命中率
    /// </summary>
    public readonly float HIT;
    /// <summary>
    /// 闪避率
    /// </summary>
    public readonly float EVA;
    /// <summary>
    /// 暴击率
    /// </summary>
    public readonly float CR;
    /// <summary>
    /// 暴击伤害倍数
    /// </summary>
    public readonly float CD;
    /// <summary>
    /// 招架/格挡率
    /// </summary>
    public readonly float PAR;
    /// <summary>
    /// 招架减伤
    /// </summary>
    public readonly float PDR;
    /// <summary>
    /// 反击率
    /// </summary>
    public readonly float CTR;
    /// <summary>
    /// 异常抗性
    /// </summary>
    public readonly float RES;
   
    public const int __ID__ = 1576771551;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "HP:" + HP + ","
        + "MP:" + MP + ","
        + "ATKp:" + ATKp + ","
        + "ATKm:" + ATKm + ","
        + "DEFp:" + DEFp + ","
        + "DEFm:" + DEFm + ","
        + "SPD:" + SPD + ","
        + "PenP:" + PenP + ","
        + "PenM:" + PenM + ","
        + "HIT:" + HIT + ","
        + "EVA:" + EVA + ","
        + "CR:" + CR + ","
        + "CD:" + CD + ","
        + "PAR:" + PAR + ","
        + "PDR:" + PDR + ","
        + "CTR:" + CTR + ","
        + "RES:" + RES + ","
        + "}";
    }
}
}

