
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.attr
{
public partial class TbActorBaseAttr
{
    private readonly System.Collections.Generic.Dictionary<string, attr.ActorBaseAttr> _dataMap;
    private readonly System.Collections.Generic.List<attr.ActorBaseAttr> _dataList;
    
    public TbActorBaseAttr(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, attr.ActorBaseAttr>(n);
        _dataList = new System.Collections.Generic.List<attr.ActorBaseAttr>(n);
        for(int i = n ; i > 0 ; --i)
        {
            attr.ActorBaseAttr _v;
            _v = global::cfg.attr.ActorBaseAttr.DeserializeActorBaseAttr(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, attr.ActorBaseAttr> DataMap => _dataMap;
    public System.Collections.Generic.List<attr.ActorBaseAttr> DataList => _dataList;

    public attr.ActorBaseAttr GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public attr.ActorBaseAttr Get(string key) => _dataMap[key];
    public attr.ActorBaseAttr this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

