
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.attr
{
public partial class TbBaseAttr
{
    private readonly System.Collections.Generic.Dictionary<string, attr.BaseAttr> _dataMap;
    private readonly System.Collections.Generic.List<attr.BaseAttr> _dataList;
    
    public TbBaseAttr(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, attr.BaseAttr>(n);
        _dataList = new System.Collections.Generic.List<attr.BaseAttr>(n);
        for(int i = n ; i > 0 ; --i)
        {
            attr.BaseAttr _v;
            _v = global::cfg.attr.BaseAttr.DeserializeBaseAttr(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, attr.BaseAttr> DataMap => _dataMap;
    public System.Collections.Generic.List<attr.BaseAttr> DataList => _dataList;

    public attr.BaseAttr GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public attr.BaseAttr Get(string key) => _dataMap[key];
    public attr.BaseAttr this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

