
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum SkillType_NeiWai
    {
        /// <summary>
        /// 内功
        /// </summary>
        NEI = 0,
        /// <summary>
        /// 外功
        /// </summary>
        WAI = 1,
    }

} 

