
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum SkillType_Weapon
    {
        /// <summary>
        /// 拳法
        /// </summary>
        QUAN = 0,
        /// <summary>
        /// 腿法
        /// </summary>
        TUI = 1,
        /// <summary>
        /// 剑法
        /// </summary>
        JIAN = 2,
        /// <summary>
        /// 刀法
        /// </summary>
        DAO = 3,
        /// <summary>
        /// 暗器
        /// </summary>
        AN = 4,
        /// <summary>
        /// 内功
        /// </summary>
        NEI = 5,
    }

} 

