
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public item.TbItem TbItem {get; }
    public attr.TbActorBaseAttr TbActorBaseAttr {get; }
    public attr.TbBaseAttr TbBaseAttr {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbItem = new item.TbItem(loader("item_tbitem"));
        TbActorBaseAttr = new attr.TbActorBaseAttr(loader("attr_tbactorbaseattr"));
        TbBaseAttr = new attr.TbBaseAttr(loader("attr_tbbaseattr"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbActorBaseAttr.ResolveRef(this);
        TbBaseAttr.ResolveRef(this);
    }
}

}
